name: torchlab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - anyio=3.7.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-auth=0.7.4
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.6
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.23.1
  - aws-sdk-cpp=1.11.156
  - babel=2.11.0
  - backcall=0.2.0
  - backoff=1.11.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.0.1
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - chroma-hnswlib=0.7.3
  - chromadb=0.4.13
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - dataclasses-json=0.5.7
  - datasets=2.12.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - filelock=3.9.0
  - flit-core=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.9.2
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.40
  - glib=2.69.1
  - glog=0.6.0
  - greenlet=2.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - h11=0.14.0
  - huggingface_hub=0.17.3
  - humanfriendly=10.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib-resources=6.1.0
  - importlib_metadata=6.0.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isoduration=20.11.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonpointer=2.4
  - jsonschema=4.17.3
  - jsonschema-with-format-nongpl=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langchain=0.0.268
  - langsmith=0.0.41
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20230802.1
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.4.2
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.57.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnuma=2.0.16
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.23.4
  - libpulsar=3.2.0
  - libsentencepiece=0.1.99
  - libsodium=1.0.18
  - libsqlite=3.41.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - marshmallow=3.19.0
  - marshmallow-enum=1.5.1
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=0.8.4
  - monotonic=1.5
  - mpmath=1.3.0
  - multidict=6.0.2
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - nltk=3.8.1
  - nomkl=3.0
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - onnxruntime=1.15.1
  - openai=0.27.4
  - openapi-schema-pydantic=1.2.4
  - openblas=0.3.23
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=3.1.3
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.4
  - pandas-stubs=1.5.3.230203
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.9.0
  - ply=3.11
  - posthog=3.0.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protobuf=4.23.4
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulsar-client=3.3.0
  - pure_eval=0.2.2
  - pyarrow=13.0.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pypika=0.48.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.0.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtconsole-base=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - responses=0.13.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.3.5
  - s2n=1.3.51
  - sacremoses=0.0.53
  - safetensors=0.3.2
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - send2trash=1.8.0
  - sentence-transformers=2.2.2
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - sentry-sdk=1.38.0
  - setproctitle=1.3.3
  - setuptools=68.0.0
  - shellingham=1.5.0.post1
  - sip=6.6.2
  - six=1.16.0
  - sleef=3.5.1
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlalchemy=2.0.21
  - sqlite=3.41.2
  - stack_data=0.2.0
  - starlette=0.27.0
  - stringcase=1.2.0
  - sympy=1.12
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenizers=0.13.3
  - toml=0.10.2
  - tomli=2.0.1
  - torchvision=0.15.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.32.1
  - typer=0.9.0
  - types-python-dateutil=2.8.19.14
  - types-pytz=2022.4.0.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucx=1.14.1
  - uri-template=1.3.0
  - urllib3=1.26.16
  - wandb=0.15.12
  - wcwidth=0.2.5
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yarl=1.8.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==23.2.1
      - altair==5.1.2
      - asyncer==0.0.2
      - bidict==0.22.1
      - chainlit==0.7.700
      - click==8.1.7
      - deprecated==1.2.14
      - fastapi==0.100.1
      - fastapi-socketio==0.0.10
      - ffmpy==0.3.1
      - filetype==1.2.0
      - googleapis-common-protos==1.62.0
      - gpt4all==1.0.12
      - gradio==3.50.2
      - gradio-client==0.6.1
      - grpcio==1.60.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - lazify==0.4.0
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-grpc==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-instrumentation==0.42b0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - orjson==3.9.10
      - pgvector==0.2.3
      - psycopg2-binary==2.9.9
      - pydub==0.25.1
      - pyjwt==2.8.0
      - pypdf==3.17.0
      - python-dotenv==1.0.0
      - python-engineio==4.8.0
      - python-graphql-client==0.4.3
      - python-multipart==0.0.6
      - python-socketio==5.10.0
      - semantic-version==2.10.0
      - simple-websocket==1.0.0
      - syncer==2.0.3
      - tiktoken==0.5.1
      - toolz==0.12.0
      - uptrace==1.21.0
      - uvicorn==0.23.2
      - watchfiles==0.20.0
      - websockets==11.0.3
      - wrapt==1.16.0
      - wsproto==1.2.0
