name: torchlab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.7.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.2.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - comm=0.1.4
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - debugpy=1.6.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - filelock=3.12.2
  - flit-core=3.9.0
  - fqdn=1.5.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.1
  - ipython=8.14.0
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.0
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libhwloc=2.9.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libmagma=2.7.1
  - libmagma_sparse=2.7.1
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - magma=2.7.1
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert-core=7.7.3
  - nbformat=5.9.2
  - nccl=2.18.3.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook-shim=0.2.3
  - numpy=1.25.2
  - openssl=3.1.2
  - overrides=7.4.0
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytorch=2.0.0
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rocm-smi=5.6.0
  - rpds-py=0.9.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.10.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - uri-template=1.3.0
  - urllib3=2.0.4
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.41.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zstd=1.5.2
